import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
//import "./globals.css";

// ★ AdSense審査通過後に GoogleAd.tsx の PUBLISHER_ID とあわせて差し替えてください
const ADSENSE_PUBLISHER_ID = "ca-pub-XXXXXXXXXXXXXXXX";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chacon Tech",
  description: "Generated by Chacon Public",
  keywords: ["Chacon", "公式", "Next.js", "Webサイト","tech","プログラミング"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {ADSENSE_PUBLISHER_ID !== "ca-pub-XXXXXXXXXXXXXXXX" && (
          <Script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_PUBLISHER_ID}`}
            crossOrigin="anonymous"
            strategy="afterInteractive"
          />
        )}
        {children}
      </body>
    </html>
  );
}