# Generated by Django 4.2 on 2025-11-11 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Tag',
            fields=[
                ('Tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_Article',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Article_id', models.IntegerField(unique=True)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Del_flg', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='T_Article_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_image', models.ImageField(upload_to='product_images/')),
                ('Overview', models.CharField(max_length=100)),
                ('Detail', models.TextField()),
                ('Related_tag_id', models.IntegerField(unique=True)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Del_flg', models.CharField(default='0', max_length=1)),
                ('Article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mypage.t_article', to_field='Article_id')),
            ],
        ),
        migrations.CreateModel(
            name='T_News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('News_body', models.TextField()),
                ('Image', models.ImageField(upload_to='news_images/')),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Del_flg', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='T_Tag_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_details', to='mypage.t_article_detail', to_field='Related_tag_id')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='mypage.m_tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='t_tag_detail',
            constraint=models.UniqueConstraint(fields=('Article_detail', 'Tag'), name='unique_tag'),
        ),
    ]
