# Generated by Django 4.2 on 2025-03-07 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Article',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Article_id', models.IntegerField(unique=True)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Del_flg', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='T_Article_Detail',
            fields=[
                ('Article_id', models.AutoField(primary_key=True, serialize=False)),
                ('Article_image', models.ImageField(upload_to='product_images/')),
                ('Overview', models.CharField(max_length=100)),
                ('Detail', models.TextField()),
                ('Related_tag_id', models.IntegerField(unique=True)),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Del_flg', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='T_News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('News_body', models.TextField()),
                ('Image', models.ImageField(upload_to='news_images/')),
                ('Create_date', models.DateTimeField(auto_now_add=True)),
                ('Del_flg', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='T_Tag_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Related_tag_id', models.IntegerField()),
                ('Tag_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddConstraint(
            model_name='t_tag_detail',
            constraint=models.UniqueConstraint(fields=('Related_tag_id', 'Tag_id'), name='unique_tag'),
        ),
    ]
