# Generated by Django 4.2 on 2025-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_t_article_t_article_detail_t_news_t_tag_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Tag',
            fields=[
                ('Tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tag_name', models.CharField(max_length=50)),
            ],
        ),
    ]
